name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy README.md
        run: |
          cp ./README.md ./packages/solid-lib/README.md

      - name: Change version
        run: |
          version=$(git describe --abbrev=0 --tags)
          sed -i -e "s/0.0.0/$version/g" packages/solid-lib/package.json
          cat packages/solid-lib/package.json
        
      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Build
        run: |
          pnpm build
      - name: Generate changelog
        run: |
          npx changelogithub # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.MY_TOKEN}}

      - name: Publish npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          cd ./packages/solid-lib
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}